tasks:
  - name: terraform
    # env:
    #   TF_LOG: DEBUG
    before: |
      source ./bin/add_tf_alias.sh 
      source ./bin/install_terraform_cli.sh
      source ./bin/generate_tfrc_credentials.sh
      cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
      source ./bin/build_provider
      cd $PROJECT_ROOT
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/add_tf_alias.sh 
      source ./bin/install_aws_cli.sh
      cd $PROJECT_ROOT
  - name: sinatra
    before: |
      cd $PROJECT_ROOT/terratowns_mock_server
      bundle install
      bundle exec ruby server.rb
      cd $PROJECT_ROOT

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
